version: '3'

services:
  app:
    container_name: app
    restart: always
    build: ./app
    environment:
      - POPPLER_PATH=/usr/local/bin/
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.maxUploadSize=2048

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app